<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJh7vvz3\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJh7vvz3/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJh7vvz3.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJh7vvz3\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerJh7vvz3\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Jh7vvz3',
    'container.build_id' => '6bf57b17',
    'container.build_time' => 1528476213,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerJh7vvz3');
